name: Hero Cypress Test
on: 
  push:
    branches:
      - main
  schedule: 
    - cron: '0 16 * * 5'
jobs:
  cypress-run:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: cypress-io/github-action@v4
        with:
          browser: chrome
          headless: true
- name: Notify Slack
  env:
    SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
  run: |
    curl -X POST -H 'Content-type: application/json' --data '{"text":"Tests have finished running"}' $SLACK_WEBHOOK_URL

