name: Hero Cypress Test
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: cypress-io/github-action@v4
        with:
          config-file: cypress.config.js
          browser: chrome
          headless: true
