name: Send Slack Alert

on:
  push:
    branches:
      - main

jobs:
  send_alert:
    runs-on: ubuntu-latest
    steps:
      - name: Send Slack notification
        uses: rtCamp/action-slack-notify@v2
        with:
          status: ${{ job.status }}
          text: 'Workflow "${{ github.workflow }}" has completed.'
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}

      - name: Notify Slack
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        run: |
          curl -X POST -H 'Content-type: application/json' --data '{"text":"Tests have finished running"}' $SLACK_WEBHOOK_URL

      - name: Send Slack Notification
        if: always()
        uses: rtCamp/action-slack-notify@v2.1.0
        with:
          status: ${{ job.status }}
          fields: repo,message,commit,author,action,eventName,ref
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          channel: cypress