name: Send Slack Alert

on:
  push:
    branches:
      - main

jobs:
  send_alert:
    runs-on: ubuntu-latest
    steps:
      - name: Send Slack notification
        uses: rtCamp/action-slack-notify@v2
        with:
          status: ${{ job.status }}
          text: 'Workflow "${{ github.workflow }}" has completed.'
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
